document new limit feature
gravwell/wiki pull request #114
Opened 2020-10-08 22:46 UTC by djfritz

2020-10-08 23:05 UTC, traetox requested changes

2020-10-08 23:05 UTC, traetox commented on search/limit/limit.md
> +The syntax is simple: `limit <n>`, where `n` is the maximum number of entries to allow through, or `limit <n> <m>`, which allows the Nth to Mth entries through. To look at the payload of 10 packets:
note that Nth to Mth is inclusive on Mth

2020-10-09 21:13 UTC, djfritz commented
PTAL @floren

2020-10-09 22:32 UTC, djfritz commented
@floren PTAL

2020-10-14 15:09 UTC, floren approved these changes

2020-10-14 15:09 UTC, merged