document simple relay regex listener
gravwell/wiki pull request #395
Opened 2022-05-05 20:32 UTC by floren

closes #394

2022-05-06 14:51 UTC, djfritz requested changes

2022-05-06 14:51 UTC, djfritz commented on ingesters/simple_relay.md
> +	Regex=`(?P<prefix><\d+>1 \d{4}-\d{1,2}-\d{1,2}T)`
```suggestion
Regex=`(?P<prefix><\d+>1 \d{4}-\d{1,2}-\d{1,2}T)`
```

2022-05-06 16:05 UTC, floren commented
ptal

2022-05-09 01:48 UTC, traetox approved these changes
LGTM

2022-05-09 16:35 UTC, merged