more warnings about s3 vs sqs
gravwell/wiki pull request #856
Opened 2023-12-08 23:14 UTC by corey-thuen-gravwell

2023-12-09 00:11 UTC, kris-watts-gravwell commented
assigning to Ashley and/or Fritz for review due to my *Exrlint Spurlin*

2023-12-11 14:31 UTC, ashnwade requested changes
We start off calling this "The Amazon S3 ingester," so it makes sense to refer to this as "the SQS ingester"

2023-12-11 14:31 UTC, ashnwade commented on ingesters/s3.md
> +If you have large amounts of S3 data and/or are interested in "tailing" S3 data, you probably should be using [SQS ingester](/ingesters/sqs) or another mechanism like (Amazon Kinesis)[/ingesters/kine
```suggestion
If you have large amounts of S3 data and/or are interested in "tailing" S3 data, you probably should be using the [SQS ingester](/ingesters/sqs) or another mechanism like (Amazon Kinesis)[/ingesters/kinesis].
```

2023-12-11 18:56 UTC, ashnwade approved these changes
LGTM

2023-12-11 18:56 UTC, merged