backup, restore, and saved search import API docs
gravwell/wiki pull request #87
Opened 2020-09-15 15:36 UTC by traetox

2020-09-15 21:13 UTC, djfritz requested changes

2020-09-15 21:13 UTC, djfritz commented on api/management.md
> +A system backup can be used to save user and group accounts, dashboards, kits, query libraries, and even saved searches.  This is essentially everything but data and system configuration.
s/system configuration/configuration files (e.g. gravwell.conf)/

2020-09-15 21:13 UTC, djfritz commented on api/management.md
> +By default a backup does not contain any saved searches, to include saved searches in the backup append the `savedsearch=true` URL parameter on the GET request.
```suggestion
By default a backup does not contain any saved searches; to include saved searches in the backup append the `savedsearch=true` URL parameter on the GET request.
```

2020-09-15 21:13 UTC, djfritz commented on api/management.md
> +Admin users may restor the system from a backup archive by performing a `POST` to the `/api/backup` API and uploading a backup file using a multipart form.
```suggestion
Admin users may restore the system from a backup archive by performing a `POST` to the `/api/backup` API and uploading a backup file using a multipart form.
```

2020-09-23 20:32 UTC, floren requested changes

2020-09-23 20:32 UTC, floren commented on api/management.md
> +A backup is obtained by performing a `GET` request on `/api/backup` as an admin user, the API will then return a file download with the backup file.
```suggestion
A backup is obtained by performing a `GET` request on `/api/backup` as an admin user. The API will then return a file download with the backup file.
```

2020-09-23 20:32 UTC, floren commented on api/searchctrl.md
> +When a search archive is reimported the search becomes owned by the user that imported it, regardless of the user that downloaded it.  An optional `GID` form field may be supplied as part of the impo
```suggestion
When a search archive is reimported, the imported search is owned by the user that *imported* it, regardless of which user *downloaded* it.  An optional `GID` form field may be supplied in the import request to share the imported search with a group.
```

2020-10-01 17:18 UTC, merged